### ISSUE TITLE
Error "to many redirects" when attempting to access login page

### ISSUE THREAD

**Issue by ThomasKoscheck** [joariasl/tuleap-docker#7]
The start-page and register-page is working.

```
==> /var/log/httpd/error_log <==
tuleap    | [Mon Jul 23 07:31:28 2018] [notice] Digest: generating secret for digest authentication ...
tuleap    | [Mon Jul 23 07:31:28 2018] [notice] Digest: done
tuleap    | [Mon Jul 23 07:31:28 2018] [warn] RSA server certificate CommonName (CN) `26ef45f4c24d' does NOT match server name!?
tuleap    | [Mon Jul 23 07:31:28 2018] [notice] Apache/2.2.15 (Unix) DAV/2 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips PHP/5.3.3 SVN/1.6.11 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
tuleap    | [Mon Jul 23 07:32:07 2018] [notice] caught SIGTERM, shutting down
tuleap    | [Mon Jul 23 07:32:16 2018] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
tuleap    | [Mon Jul 23 07:32:16 2018] [warn] RSA server certificate CommonName (CN) `26ef45f4c24d' does NOT match server name!?
tuleap    | [Mon Jul 23 07:32:16 2018] [notice] Digest: generating secret for digest authentication ...
tuleap    | [Mon Jul 23 07:32:16 2018] [notice] Digest: done
tuleap    | [Mon Jul 23 07:32:16 2018] [warn] RSA server certificate CommonName (CN) `26ef45f4c24d' does NOT match server name!?
tuleap    | 

```

Any help is appreciated

**Comment by joariasl** [comment]
Hi @ThomasKoscheck.
I can try to check it, but now Tuleap has an official and more update Docker image. Can you see: https://docs.tuleap.org/installation-guide/docker-image.html | https://hub.docker.com/r/enalean/tuleap-aio/
If you need this image for any special reason, tell me and I can see it if you send me your steps to replicate the problem.

**Comment by ThomasKoscheck** [comment]
Hi,
sorry for the late response. I used your image because it is working better than the offical one :)

I fixed this issue by leaving `$sys_https_host` in the local.ini file blank
(my setting is with https and a nginx reverse proxy

**Comment by joariasl** [comment]
I understand your problem. Regrettably Tuleap does not use relative paths.
Do you have these implementation updating to the new Tuleap versions?
Is it working OK for you?

I will to close this issue because you encountered a solution.
